---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# jjmR

<!-- badges: start -->
<!-- badges: end -->

The goal of jjmR is to ... Graphics and diagnostics libraries for SPRFMO's JJM model adopted from IMARPE's jjmTools


## Installation

You can install the development version of jjmR like so:

``` r
install.packages("devtools")
devtools::install_github("danovando/jjmR@dev")
```
## Example of tidying jjm outputs

This is a quick and dirty example of how to use new features of `jjmR` to tidy and analyze results of JJM model that will get cleaned up. 

```{r}
library(here)
library(ggplot2)
library(tidyverse)
library(jjmR)
theme_set(theme_jjm(base_size = 15))
setwd(here("assessment"))

# read in a model run
# mod0.00 <- runit(mod="h2_0.00",pdf=TRUE,est=TRUE,exec="../src/jjms")


mod0.00 <- readJJM("h2_0.00", path = "config", input = "input")

# compare to a past model run
load("results/mod_prev_h1.Rdat")

old_vs_new_mods <- combineModels(mod0.00,mod_prev)


selectivities <- get_selectivities(old_vs_new_mods)


plot_selectivities(selectivities)


plot(old_vs_new_mods,what="selectivity",fleet="fsh", alpha = 0.2, scale = 10,
     years = 2000:2020)


plot(mod0.00,what="selectivity",fleet="ind", alpha = 0.2, scale = 10,
     years = 2015:2020)

a = get_msy_mt(old_vs_new_mods)

kobe(mod0.00, engine = "ggplot")

kobe(old_vs_new_mods, engine = "lattice")

qs = get_catchabilities(mod0.00)



qs %>% 
  ggplot(aes(year, q, color = model)) + 
  geom_line() + 
  facet_wrap(~ fleet_name, scales = "free_y")


totals <- get_totals(old_vs_new_mods)


totals %>% 
  ggplot(aes(year, value, color = stock, linetype = model)) + 
  geom_line() + 
  facet_wrap(~ metric, scales = "free_y")


index_fits <- get_index_fits(old_vs_new_mods)

index_fits %>% 
  ggplot() + 
  geom_pointrange(aes(year, observed_ind, ymin = observed_ind - 1.96 * observed_se, ymax =  observed_ind + 1.96 * observed_se)) +
  geom_path(aes(year, pred_ind, color = model)) + 
  facet_wrap(~ fleet_name, scales = "free_y")


age_fits <- get_age_fits(old_vs_new_mods)


age_fits %>% 
  filter(model == "h2_0.00", stock == "Stock_1", source == "fsh_1") %>% 
  pivot_longer(predicted:observed) %>% 
  ggplot() + 
  geom_density(aes(age, value, fill = name),stat = "identity", alpha = 0.5) + 
  facet_wrap(~year)


recruits <- get_recruits(old_vs_new_mods)

recruits %>% 
  ggplot() + 
  geom_ribbon(aes(year, ymin = lower_recruits, ymax = upper_recruits, fill = stock),alpha = 0.5) + 
  geom_line(aes(year, recruits, color = stock)) + 
  facet_wrap(~model)



fishing_mortality <- get_fishing_mortality(old_vs_new_mods)

fishing_mortality %>% 
  ggplot(aes(year, mortality, color = age, group = age)) + 
  geom_line() + 
  facet_grid(model~stock)

tidy_jjm <- tidy_JJM(old_vs_new_mods)
str(tidy_jjm)

```



