#' Print method for jjm.output objects
#'
#' Prints a summary of the JJM model output object, displaying basic information
#' about the model, stocks, and data sources.
#'
#' @param x An object of class 'jjm.output'
#' @param ... Additional arguments passed to print methods
#'
#' @return Invisibly returns the input object (for use in pipelines)
#' @export
#' 
#' @examples
#' \dontrun{
#' model <- read.jjm("path/to/model")
#' print(model)
#' }
print.jjm.output <- function(x, ...) {
  
  for(i in seq_along(x)) {
    obj <- x[[i]]
    
    cat("JJM version: ", obj$info$data$version, "\n")
    cat("Model name: ", obj$info$output$model, "\n")
    cat("Stock number: ", paste(obj$info$output$nStock, collapse = ", "), "\n")
    
    if(obj$info$data$version == "2015MS") {
      stockNames <- strsplit(obj$control$nameStock, "%")[[1]]
      cat("Stock names: ", paste(stockNames, collapse = ", "), "\n")
    }
    
    cat("Number of variables: ", obj$info$data$variables, "\n")
    cat("Years from: ", obj$info$data$year[1], " to ", obj$info$data$year[2], "\n")
    cat("Ages from: ", obj$info$data$age[1], " to ", obj$info$data$age[2], "\n")
    cat("Lengths from: ", obj$info$data$length[1], " to ", obj$info$data$length[2], "\n")
    cat("Fisheries names: ", paste(obj$info$output$fisheryNames, collapse = ", "), "\n")
    cat("Associated indices: ", paste(obj$info$output$indexModel, collapse = ", "), "\n")
    cat("jjm.data from ", sQuote(obj$info$data$file), "\n")
    cat("\n")
  }
  
  return(invisible(x))
}

#' Summary method for jjm.output objects
#'
#' Generates a detailed summary of the JJM model output, including parameter tables,
#' likelihood tables, projection tables (if requested), and summary plots.
#'
#' @param object An object of class 'jjm.output'
#' @param Projections Logical. Whether to include projection tables. Default is FALSE.
#' @param Fmult Optional vector of F multipliers for projections
#' @param BiomProj Optional biomass projection parameters
#' @param CapProj Optional capacity projection parameters
#' @param MRS Optional Maximum Relative Selectivity parameters
#' @param ... Additional arguments passed to internal plotting functions
#'
#' @return An object of class 'summary.jjm.output' containing tables and plots
#' @export
#'
#' @examples
#' \dontrun{
#' model <- read.jjm("path/to/model")
#' model_summary <- summary(model, Projections = TRUE)
#' print(model_summary)
#' }
summary.jjm.output <- function(object, Projections = FALSE, Fmult = NULL,
                              BiomProj = NULL, CapProj = NULL, MRS = NULL, ...) {
  
  pic <- list()
  namesPlot <- NULL
  
  for(i in seq_along(object)) {
    jjm.stocks <- object[[i]]$output
    
    for(j in seq_along(jjm.stocks)) {
      jjm.out <- jjm.stocks[[j]]
      jjm.in <- object[[i]]$data
      jjm.ypr <- jjm.stocks[[j]]$YPR
      namesPlot[j] <- as.list(names(object[[i]]$output))[[j]]
      
      pic[[j]] <- .fit_summarySheet3FUN(jjm.out, 
                                        scales = list(alternating = 1, 
                                                     tck = c(1, 0),
                                                     y = list(relation = "free", rot = 0),
                                                     axs = "i"), ...)
    }
  }
  
  names(pic) <- namesPlot
  
  output <- list()
  output$parameters <- .ParTable(object)
  output$like <- .LikeTable(object)
  output$projections <- .ProjTable(object, Projections = Projections,
                                  Fmult = Fmult, BiomProj = BiomProj, 
                                  CapProj = CapProj, MRS = MRS)
  output$plots <- pic
    
  class(output) <- "summary.jjm.output"
  
  return(output)
}

#' Print method for summary.jjm.output objects
#'
#' Prints the tables and plots generated by the summary method for jjm.output objects.
#'
#' @param x An object of class 'summary.jjm.output'
#' @param ... Additional arguments passed to print methods
#'
#' @return Invisibly returns the input object (for use in pipelines)
#' @export
print.summary.jjm.output <- function(x, ...) {
  cat("\nParameter Table:\n\n")
  print(x$parameters, ...)
  
  cat("\nLikelihood Table:\n\n")
  print(x$like, ...)
  
  if(!is.null(x$projections)) {
    cat("\nProjection Table(s):\n\n")
    
    for(i in seq_along(x$projections)) {
      cat(names(x$projections)[i], "\n")
      print(x$projections[[i]], ...)
      cat("\n")
    }
  }
  
  cat("\nSummary Plot(s):\n\n")
  
  for(i in seq_along(x$plots)) {
    cat(names(x$plots)[i], "\n")
    grid.newpage()
    grid.draw(x$plots[[i]])
  }
  
  return(invisible(x))
}

#' Plot method for jjm.output objects
#'
#' Creates various plots from the JJM model output based on the specified type.
#'
#' @param x An object of class 'jjm.output'
#' @param what Character string specifying the type of plot. Options include:
#'   \itemize{
#'     \item "biomass" - Plot biomass over time
#'     \item "recruitment" - Plot recruitment over time
#'     \item "ssb" - Plot spawning stock biomass over time
#'     \item "noFishTB" - Plot unfished total biomass
#'     \item "ftot" - Plot total fishing mortality
#'     \item "kobe" - Create a Kobe plot
#'     \item "catchProj" - Plot catch projections
#'     \item "ssbProj" - Plot SSB projections
#'     \item "totalProj" - Plot total projections
#'     \item "catchProjScen" - Plot catch projection scenarios
#'     \item "ssbProjScen" - Plot SSB projection scenarios
#'     \item "ratioSSB_F" - Plot ratio of SSB to F
#'     \item "ratioSSB" - Plot ratio of SSB
#'     \item "selectivity" - Plot selectivity curves
#'   }
#' @param stack Logical. If TRUE, stack multiple series in one plot. Default is TRUE.
#' @param endvalue Logical. If TRUE, display end values on plot. Default is FALSE.
#' @param total Logical. If TRUE, include total values. Default is FALSE.
#' @param combine Logical. If TRUE, combine multiple plots. Default is FALSE.
#' @param cols Optional vector of colors for plotting
#' @param poslegend Position of the legend. Default is "right".
#' @param scen Integer. Scenario number for projection plots. Default is 1.
#' @param ... Additional arguments passed to plotting functions
#'
#' @return A plot object (typically a grid or ggplot object)
#' @export
#'
#' @examples
#' \dontrun{
#' model <- read.jjm("path/to/model")
#' plot(model, what = "biomass")
#' plot(model, what = "ssb", stack = FALSE)
#' plot(model, what = "kobe")
#' }
plot.jjm.output <- function(x, what = "biomass", stack = TRUE, endvalue = FALSE, 
                           total = FALSE, combine = FALSE, cols = NULL, 
                           poslegend = "right", scen = 1, ...) {
  
  switch(what,
         biomass = .funPlotSeries(x, what, cols, stack, endvalue, poslegend, total, combine, ...),
         recruitment = .funPlotSeries(x, what, cols, stack, endvalue, poslegend, total, combine, ...),
         ssb = .funPlotSeries(x, what, cols, stack, endvalue, poslegend, total, combine, ...),
         noFishTB = .funPlotSeries(x, what, cols, stack, endvalue, poslegend, total, combine, ...),
         ftot = .funPlotSeries(x, what, cols, stack, endvalue, poslegend, total, combine, ...),
         kobe = .funPlotKobe(x, what, cols, stack, endvalue, poslegend, ...),
         catchProj = .funPlotProj(x, what, cols, stack, endvalue, poslegend, ...),
         ssbProj = .funPlotProj(x, what, cols, stack, endvalue, poslegend, ...),
         totalProj = .funPlotTotProj(x, what, cols, stack, endvalue, poslegend, scen, ...),
         catchProjScen = .funPlotScen(x, what, cols, stack, endvalue, poslegend, ...),
         ssbProjScen = .funPlotScen(x, what, cols, stack, endvalue, poslegend, ...),
         ratioSSB_F = .funPlotRatioSSB_F(x, what, cols, stack, endvalue, poslegend, ...),
         ratioSSB = .funPlotRatioSSB(x, what, cols, stack, endvalue, poslegend, ...),
         selectivity = plot_selectivities(get_selectivities(x), ...))
}
